language: go

go:
- 1.18

install:
- go get -v -t ./...
- go install github.com/mattn/goveralls@latest

script:
- go vet ./...
- go test ./... -cover=1 -coverprofile=_c.cov
- go test ./... -race

after_script:
- $GOPATH/bin/goveralls -service=travis-ci -coverprofile=_c.cov
